# Generated by Django 4.1.1 on 2022-10-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.TextField(),
        ),
    ]
