# Generated by Django 4.1.1 on 2022-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='text',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='text',
            name='libele',
            field=models.TextField(),
        ),
    ]
