# Generated by Django 4.1.1 on 2022-10-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_banner_title_alter_text_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousservice',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
