# Generated by Django 4.1.1 on 2022-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sousservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='picturePhone',
            field=models.FileField(default=1, upload_to='img_banner'),
            preserve_default=False,
        ),
    ]
