# Generated by Django 4.1.1 on 2023-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_commandes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publish", models.BooleanField(default=True)),
                ("date_add", models.DateField(auto_now_add=True)),
                ("date_update", models.DateField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
    ]
