# Generated by Django 4.1.1 on 2023-02-25 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_contact_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
    ]
