# Generated by Django 4.1.1 on 2023-02-25 11:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_remove_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
