# Generated by Django 4.1.1 on 2023-02-26 02:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
