# Generated by Django 4.1.1 on 2023-02-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_about_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="libele",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
