# Generated by Django 4.1.1 on 2023-03-10 23:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_service_libele"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousservice",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
