# Generated by Django 4.1.1 on 2023-03-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_sousservice_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referencement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publish", models.BooleanField(default=True)),
                ("date_add", models.DateField(auto_now_add=True)),
                ("date_update", models.DateField(auto_now=True)),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("keyword", models.TextField()),
            ],
            options={
                "verbose_name": "RÉFÉRENCEMENT",
                "verbose_name_plural": "RÉFÉRENCEMENT",
            },
        ),
    ]
