# Generated by Django 4.1.1 on 2023-03-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_referencement"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencement",
            name="author",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
