# Generated by Django 4.1.1 on 2023-03-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_referencement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='pictureContact',
            field=models.FileField(default=1, upload_to='img_banner_contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='pictureInscription',
            field=models.FileField(default=1, upload_to='img_banner_inscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='pictureReservation',
            field=models.FileField(default=1, upload_to='img_banner_reservation'),
            preserve_default=False,
        ),
    ]
