# Generated by Django 4.1.1 on 2023-03-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_banner_picturecontact_banner_pictureinscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestatire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=250)),
                ('date_time', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Nos Jobbers',
                'verbose_name_plural': 'Nos Jobbers',
            },
        ),
    ]
