# Generated by Django 4.1.1 on 2023-03-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_prestatire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestatire',
            name='date_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prestatire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prestatire',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prestatire',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prestatire',
            name='service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
