# Generated by Django 4.1.1 on 2023-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_prestatire_date_time_alter_prestatire_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Nos Conditions Generales',
                'verbose_name_plural': 'Nos Conditions Generales',
            },
        ),
    ]
