# Generated by Django 4.1.1 on 2023-04-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_prestatire_date_time_prestatire_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatire',
            old_name='resto',
            new_name='recto',
        ),
    ]
