# Generated by Django 4.1.1 on 2023-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_resto_prestatire_recto'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatire',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
