# Generated by Django 4.1.1 on 2023-05-29 13:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_prestatire_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Mentions Legales',
                'verbose_name_plural': 'Mentions Legales',
            },
        ),
    ]
