# Generated by Django 4.1.1 on 2023-05-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('libele', models.TextField()),
            ],
            options={
                'verbose_name': 'Metiers',
                'verbose_name_plural': 'Metiers',
            },
        ),
    ]
