# Generated by Django 4.1.1 on 2023-05-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_metier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestatire',
            old_name='service',
            new_name='metier',
        ),
    ]
