# Generated by Django 4.1.1 on 2023-05-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_service_prestatire_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
