# Generated by Django 4.1.1 on 2023-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_web_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='commandes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
