# Generated by Django 4.1.1 on 2023-05-29 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_about_date_add_alter_askservice_date_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatire',
            name='hours',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
